# Credit Lütfü Mert Ceylan (@lutfumertceylan):
# https://twitter.com/lutfumertceylan/status/1272895185031217152

OPEN_REDIRECT_DORKS = ['next',
                       'url',
                       'target',
                       'rurl',
                       'dest',
                       'destination',
                       'redir',
                       'redirect_url',
                       'redirect_uri',
                       'redirect',
                       'view',
                       'to',
                       'go',
                       'image_url',
                       'return',
                       'returnTo',
                       'return_to',
                       'returnurl',
                       'ReturnUrl',
                       'checkout_url',
                       'continue',
                       'return_path',]
